name: 🤖 Engineering Agent Task
description: Trigger the Engineering Agent to perform automated development tasks
title: "[Agent Task]: "
labels: ["agent-task", "automation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Engineering Agent Task Request
        Use this form to request the Engineering Agent to perform automated development tasks such as code generation, refactoring, testing, or documentation.

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What type of task should the agent perform?
      options:
        - Feature Implementation
        - Bug Fix
        - Code Refactoring
        - Test Generation
        - Documentation
        - Code Review
        - Performance Optimization
        - Security Fix
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Provide a clear and detailed description of what the agent should do
      placeholder: |
        Example: Implement a new authentication middleware that validates JWT tokens and handles refresh token rotation.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this task to be considered complete?
      placeholder: |
        - [ ] Authentication middleware is implemented
        - [ ] Unit tests are added with >80% coverage
        - [ ] Documentation is updated
        - [ ] No breaking changes to existing API
    validations:
      required: true

  - type: input
    id: affected-files
    attributes:
      label: Affected Files/Modules
      description: Specify which files or modules should be modified (comma-separated)
      placeholder: "src/auth/middleware.ts, tests/auth.test.ts, docs/api.md"

  - type: dropdown
    id: requires-review
    attributes:
      label: Requires Human Review
      description: Should a human review the changes before merging?
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information, links, or context that might help the agent
      placeholder: |
        - Related issues: #123
        - Documentation: https://example.com/docs
        - Design considerations: ...

  - type: input
    id: branch-name
    attributes:
      label: Target Branch
      description: Which branch should the agent create the PR against?
      placeholder: "main"
      value: "main"

  - type: checkboxes
    id: agent-capabilities
    attributes:
      label: Required Agent Capabilities
      description: Select the capabilities the agent should use
      options:
        - label: Code Generation
        - label: Testing
        - label: Documentation
        - label: Code Analysis
        - label: Dependency Management
        - label: CI/CD Configuration

  - type: markdown
    attributes:
      value: |
        ---
        **Note:** Once submitted, the Engineering Agent will be triggered automatically. You can monitor progress through status updates on this issue.
